name: Run Script on Issue Form Submission

on:
  issues:
    types:
      - opened

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests tqdm wikidataintegrator

      - name: Parse issue and extract parameters
        id: parse-issue
        run: |
          echo "Extracting issue details..."
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "$ISSUE_BODY" > issue_content.txt

          # Extract taxon_id, username, country_code, or project_id from issue form
          TAXON_ID=$(echo "$ISSUE_BODY" | grep -oP 'Taxon ID:\s*\K\d+')
          USERNAME=$(echo "$ISSUE_BODY" | grep -oP 'Username:\s*\K\S+')
          COUNTRY_CODE=$(echo "$ISSUE_BODY" | grep -oP 'Country Code:\s*\K\d+')
          PROJECT_ID=$(echo "$ISSUE_BODY" | grep -oP 'Project ID:\s*\K\S+')

          # Set GitHub Actions environment variables
          echo "taxon_id=$TAXON_ID" >> $GITHUB_ENV
          echo "username=$USERNAME" >> $GITHUB_ENV
          echo "country_code=$COUNTRY_CODE" >> $GITHUB_ENV
          echo "project_id=$PROJECT_ID" >> $GITHUB_ENV

      - name: Run the script
        run: |
          if [[ -n "$taxon_id" ]]; then
            python script.py taxon "$taxon_id"
          elif [[ -n "$username" ]]; then
            python script.py user "$username"
          elif [[ -n "$country_code" ]]; then
            python script.py country "$country_code"
          elif [[ -n "$project_id" ]]; then
            python script.py project "$project_id"
          else
            echo "No valid parameters found in the issue. Exiting..."
            exit 1
          fi

      - name: Upload generated markdown report
        uses: actions/upload-artifact@v4
        with:
          name: missing-wikipedia-report
          path: suggestions/
